<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Apply Details' => '',
    'Confirmation is failed, because Order already {status}' => '',
    'Datetime format must be `Y-m-d H:i:s` eg: 2017-01-30 19:00:50' => '',
    'Invalid login or password' => '',
    'Now, Order is not actived.' => '',
    'Order is not found.' => '',
    'Order status cannot be change to {status}' => '',
    'Order status cannot change to ' => '',
    'Position or Company' => '',
    'This Partner cannot be create order again, because already order still actived.' => '',
    'This User cannot be create order again, because already order still actived.' => '',
    'This partner is no limit.' => '',
    'This partner is not order actived.' => '',
    'User Details' => '',
    'Welcome to {name}' => '',
];
