<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => '',
    'Button is disabled because your data is not completed.' => '',
    'Cities' => '',
    'Click if your company isn\'t registered' => '',
    'Companies' => '',
    'Create' => '',
    'Create Company' => '',
    'Create Job' => '',
    'Create Partner' => '',
    'Create Partner Branch' => '',
    'Create Partner Has User' => '',
    'Currencies' => '',
    'Data is successfully saved' => '',
    'Delete' => '',
    'Educations' => '',
    'Goto Partner' => '',
    'Goto User' => '',
    'Job Applies' => '',
    'Job Apply' => '',
    'Job Types' => '',
    'Jobs' => '',
    'Label' => '',
    'List Branches' => '',
    'List Companies' => '',
    'List Jobs' => '',
    'List Members' => '',
    'Name' => '',
    'Notes' => '',
    'Offer Types' => '',
    'Offers' => '',
    'Order' => '',
    'Order Confirmation' => '',
    'Order still Active' => '',
    'Orders' => '',
    'Pages' => '',
    'Partner Branches' => '',
    'Partner Companies' => '',
    'Partner Has Users' => '',
    'Partners' => '',
    'Passions' => '',
    'Payment Types' => '',
    'Payments' => '',
    'Provinces' => '',
    'Reset' => '',
    'Search' => '',
    'Skills' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'User Companies' => '',
    'Value' => '',
    'View your company' => '',
    'Visitors' => '',
    'Walk in Interview' => '',
];
